import {
  CENTRAL_RECEIVING_ROUTE,
  CENTRAL_ROUTING_LIST_ROUTE,
  RECEIVING_ROUTE,
  ROUTING_LIST_ROUTE,
} from '../../constants';

export const FALLBACK_ROUTE = RECEIVING_ROUTE;
export const ROUTING_LIST_CREATE_ROUTE = `${ROUTING_LIST_ROUTE}/create/:poLineId`;
export const ROUTING_LIST_EDIT_ROUTE = `${ROUTING_LIST_ROUTE}/edit/:id`;
export const ROUTING_LIST_VIEW_ROUTE = `${ROUTING_LIST_ROUTE}/view/:id`;

export const CENTRAL_FALLBACK_ROUTE = CENTRAL_RECEIVING_ROUTE;
export const CENTRAL_ROUTING_LIST_CREATE_ROUTE = `${CENTRAL_ROUTING_LIST_ROUTE}/create/:poLineId`;
export const CENTRAL_ROUTING_LIST_EDIT_ROUTE = `${CENTRAL_ROUTING_LIST_ROUTE}/edit/:id`;
export const CENTRAL_ROUTING_LIST_VIEW_ROUTE = `${CENTRAL_ROUTING_LIST_ROUTE}/view/:id`;
